spring:
  application:
    name: customer
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/feignclient
    username: postgres
    password: 12345
server:
  port: 8081