spring:
  application:
    name: product
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/feignclient
    username: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8082