spring:
  application:
    name: order
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/feignclient
server:
  port: 8083